name: CI

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install clang-format
      - run: make
      - run: make check
      - run: make test-unit

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
